Traceback (most recent call last):
  File "<ipython-input-281-ba6b8fb8915f>", line 4, in <module>
    raise Exception('This is an error message')
Exception: This is an error message
